{% set version = "1.10.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-dendextend
  version: {{ version|replace("-", "_") }}

source:
  fn: dendextend_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/dendextend_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/dendextend/dendextend_{{ version }}.tar.gz
  sha256: 88f0fb3362d69144daf4f35d0ea09f32c2df1adf614e040327a42552a8fd3224

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-fpc
    - r-ggplot2
    - r-magrittr >=1.0.1
    - r-viridis
    - r-whisker
  run:
    - r-base
    - r-fpc
    - r-ggplot2
    - r-magrittr >=1.0.1
    - r-viridis
    - r-whisker

test:
  commands:
    - $R -e "library('dendextend')"           # [not win]
    - "\"%R%\" -e \"library('dendextend')\""  # [win]

about:
  home: https://github.com/talgalili/dendextend/, https://cran.r-project.org/package=dendextend,
    https://www.r-statistics.com/tag/dendextend/, https://academic.oup.com/bioinformatics/article/31/22/3718/240978/dendextend-an-R-package-for-visualizing-adjusting
  license: GPL-2 | GPL-3
  summary: Offers a set of functions for extending 'dendrogram' objects in R, letting you visualize
    and compare trees of 'hierarchical clusterings'. You can (1) Adjust a tree's graphical
    parameters - the color, size, type, etc of its branches, nodes and labels. (2) Visually
    and statistically compare different 'dendrograms' to one another.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
