{% set version = "1.14.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-dendextend
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/dendextend_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/dendextend/dendextend_{{ version }}.tar.gz
  sha256: 3789461bc474e146b077ad26566b1fa05be32fc7e57ab1fb5e78bdabcc797858

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-ggplot2
    - r-magrittr >=1.0.1
    - r-viridis
  run:
    - r-base
    - r-ggplot2
    - r-magrittr >=1.0.1
    - r-viridis

test:
  commands:
    - $R -e "library('dendextend')"           # [not win]
    - "\"%R%\" -e \"library('dendextend')\""  # [win]

about:
  home: https://github.com/talgalili/dendextend/, https://cran.r-project.org/package=dendextend, https://www.r-statistics.com/tag/dendextend/, https://academic.oup.com/bioinformatics/article/31/22/3718/240978/dendextend-an-R-package-for-visualizing-adjusting
  license: GPL-2.0-or-later
  summary: Offers a set of functions for extending 'dendrogram' objects in R, letting you visualize and compare trees of 'hierarchical clusterings'. You can (1) Adjust a tree's graphical parameters - the color, size, type, etc of its branches, nodes and labels. (2) Visually and statistically compare different 'dendrograms'
    to one another.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: dendextend
# Type: Package
# Title: Extending 'dendrogram' Functionality in R
# Version: 1.12.0
# Date: 2019-05-11
# Authors@R: c(person("Tal", "Galili", role = c("aut", "cre", "cph"), email = "tal.galili@gmail.com", comment = "https://www.r-statistics.com"), person("Yoav", "Benjamini", email = "ybenja@tau.ac.il",role = "ths"), person("Gavin", "Simpson", role = "ctb"), person("Gregory","Jefferis", role = c("aut", "ctb"), email = "jefferis@gmail.com", comment ="imported code from his dendroextras package"), person("Marco", "Gallotta", role = "ctb", comment = "a.k.a: marcog") , person("Johan", "Renaudie", role = "ctb", comment = "https://github.com/plannapus"), person("The R Core Team", role = "ctb", comment = "Thanks for the Infastructure, and code in the examples"), person("Kurt", "Hornik", role = "ctb"), person("Uwe", "Ligges", role = "ctb"), person("Andrej-Nikolai", "Spiess", role = "ctb"), person("Steve", "Horvath",email = "SHorvath@mednet.ucla.edu", role = "ctb"), person("Peter", "Langfelder",email = "Peter.Langfelder@gmail.com", role = "ctb"), person("skullkey", role = "ctb"), person("Mark", "Van Der Loo", email = "mark.vanderloo@gmail.com", comment = "https://github.com/markvanderloo d3dendrogram", role = "ctb"), person("Andrie", "de Vries", email = "apdevries@gmail.com", comment = "ggdendro author", role = "ctb"), person("Zuguang", "Gu", email = "z.gu@dkfz-heidelberg.de", comment = "circlize author", role = "ctb"),     person("Cath", comment = "https://github.com/CathG", role = "ctb"), person("John", "Ma", comment = "https://github.com/JohnMCMa", role = "ctb"), person("Krzysiek", "G", comment = "https://github.com/storaged", role = "ctb"), person("Manuela", "Hummel", email = "m.hummel@dkfz.de", comment = "https://github.com/hummelma", role = "ctb"),  person("Chase", "Clark", comment = "https://github.com/chasemc", role = "ctb"),  person("Lucas", "Graybuck", comment = "https://github.com/hypercompetent", role = "ctb"),  person("jdetribol", comment = "https://github.com/jdetribol", role = "ctb"),  person("Ben", "Ho", role = "ctb", email = "ben.ho@sickkids.ca", comment = "https://github.com/SplitInf"), person("Samuel", "Perreault", role = "ctb", email = "samuel.perreault.3@ulaval.ca", comment = "https://github.com/samperochkin"), person("Christian", "Hennig", role = "ctb", email = "c.hennig@ucl.ac.uk", comment = "http://www.homepages.ucl.ac.uk/~ucakche/"))
# Description: Offers a set of functions for extending 'dendrogram' objects in R, letting you visualize and compare trees of 'hierarchical clusterings'. You can (1) Adjust a tree's graphical parameters - the color, size, type, etc of its branches, nodes and labels. (2) Visually and statistically compare different 'dendrograms' to one another.
# Depends: R (>= 3.0.0)
# Imports: utils, stats, datasets, magrittr (>= 1.0.1), ggplot2, viridis
# Suggests: knitr, rmarkdown, testthat, seriation, colorspace, ape, profdpm, microbenchmark, gplots, heatmaply, d3heatmap, dynamicTreeCut, pvclust, corrplot, DendSer, MASS, cluster, fpc, circlize (>= 0.2.5), covr
# Enhances: ggdendro, dendroextras, Hmisc, data.table, rpart
# VignetteBuilder: knitr
# LazyData: true
# License: GPL-2 | GPL-3
# URL: https://github.com/talgalili/dendextend/, https://cran.r-project.org/package=dendextend, https://www.r-statistics.com/tag/dendextend/, https://academic.oup.com/bioinformatics/article/31/22/3718/240978/dendextend-an-R-package-for-visualizing-adjusting
# BugReports: https://github.com/talgalili/dendextend/issues
# RoxygenNote: 6.1.1
# NeedsCompilation: no
# Packaged: 2019-05-11 11:59:11 UTC; junior
# Author: Tal Galili [aut, cre, cph] (https://www.r-statistics.com), Yoav Benjamini [ths], Gavin Simpson [ctb], Gregory Jefferis [aut, ctb] (imported code from his dendroextras package), Marco Gallotta [ctb] (a.k.a: marcog), Johan Renaudie [ctb] (https://github.com/plannapus), The R Core Team [ctb] (Thanks for the Infastructure, and code in the examples), Kurt Hornik [ctb], Uwe Ligges [ctb], Andrej-Nikolai Spiess [ctb], Steve Horvath [ctb], Peter Langfelder [ctb], skullkey [ctb], Mark Van Der Loo [ctb] (https://github.com/markvanderloo d3dendrogram), Andrie de Vries [ctb] (ggdendro author), Zuguang Gu [ctb] (circlize author), Cath [ctb] (https://github.com/CathG), John Ma [ctb] (https://github.com/JohnMCMa), Krzysiek G [ctb] (https://github.com/storaged), Manuela Hummel [ctb] (https://github.com/hummelma), Chase Clark [ctb] (https://github.com/chasemc), Lucas Graybuck [ctb] (https://github.com/hypercompetent), jdetribol [ctb] (https://github.com/jdetribol), Ben Ho [ctb] (https://github.com/SplitInf), Samuel Perreault [ctb] (https://github.com/samperochkin), Christian Hennig [ctb] (http://www.homepages.ucl.ac.uk/~ucakche/)
# Maintainer: Tal Galili <tal.galili@gmail.com>
# Repository: CRAN
# Date/Publication: 2019-05-11 12:30:03 UTC
