travis:
  secure:
    BINSTAR_TOKEN: asv/ZnSBAD5W3XTAX5GKyuyCYG9vJRvOXrt2y2owfjeM4yLIhxybRTe7tAX8xfEbe/fQHrWdjU6vRA9z4R0qwW6/eQ74bHaJbIxbH3bbDyIRAbxGuYLiN8IcAt/RWDbgllI+X0tS9t8/AP/pN5IvbRDnO48mplN3TGzMiyinrQbl4vHPt520YIGT7bk2jfQPmYywM0J5ytNCKiSvh+Fn+VOoG9YnBLQWIgWEGk8haPajd51L0cQ1zVw/y4MC5H68FW7BLcrsrr78kbC5iQFLkLRJrQPzdVG4XXtDQ+QrJncdQgWL7Wwk+BYJa8z8T7KiQTlCYKTVVuvYuUMBZvR25sNwWmOh9EjEEgvZou1hZ4LQ3BnVg/BS8UpMcElwXE6Po28ioyutopSjY5Iqj+NnzrDfODdIQDHs892XrGOY71BDVSaO8ZPyv2I5tas+PgW2nayX/c0+Vr6dlOXFzu9sahoOhFrJ3dNFgGuYSauO9OoH/0VRdrn4D0dUPvL5PxhGrfaSL/EXOqu+McX/jwbjlc1WA7byeBGhxH+Hol8cDsLKz50wCtxsT+G/N05Hg3bHBsYY27CF+QIV+kJxGQbpQttzW+a4QDgE2sprH+txuiWpkwKivycfMzZwkCaERiIKCDMAOwLpLYXqH/FGGKN/cDZq6w/AMDqT57QH75BUOCs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
